my_project_dbt:  # Nome do projeto dbt
  target: dev   # Alvo de execução (dev, prod, etc.)
  outputs:
    dev:       # Configuração do alvo 'dev'
      type: snowflake
      user:  "{{ env_var('SNOWFLAKE_USER')}}"
      account: "{{ env_var('SNOWFLAKE_ACCOUNT')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      schema: dev
      warehouse: "{{ env_var('SNOWFLAKE_WH')}}"
      threads: 5  
      ##client_session_keep_alive: False
      ##query_tag: [anything]
    pr:       # Configuração do alvo 'dev'
      type: snowflake
      user:  "{{ env_var('SNOWFLAKE_USER')}}"
      account: "{{ env_var('SNOWFLAKE_ACCOUNT')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      schema: pr_{{ var('schema_id')}}
      warehouse: "{{ env_var('SNOWFLAKE_WH')}}"
      threads: 5  
    
    pr:       # Configuração do alvo 'dev'
      type: snowflake
      user:  "{{ env_var('SNOWFLAKE_USER')}}"
      account: "{{ env_var('SNOWFLAKE_ACCOUNT')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      schema: prod
      warehouse: "{{ env_var('SNOWFLAKE_WH')}}"
      threads: 5  

## POSTGRES ##
## By default, edr expects the profile name 'elementary'.      ##
## Configure the database and schema of elementary models.     ##
## Check where 'elementary_test_results' is to find it.        ##

elementary:
  enable: false
  outputs:
    elementary_dev:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER')}}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      warehouse: "{{ env_var('SNOWFLAKE_WH')}}"
      schema: dev
      threads: 4
    
    elementary_prod:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER')}}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      warehouse: "{{ env_var('SNOWFLAKE_WH')}}"
      schema: prod
      threads: 4
    
    elementary_pr:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER')}}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE')}}"
      database: "{{ env_var('SNOWFLAKE_DATABASE')}}"
      warehouse: "{{ env_var('SNOWFLAKE_WH')}}"
      schema: pr_{{ var('schema_id')}}
      threads: 4