my_project_dbt:  # Nome do projeto dbt
  target: dev   # Alvo de execução (dev, prod, etc.)
  outputs:
    dev:       # Configuração do alvo 'dev'
    
      type: snowflake
      user:  "{{env_var('DBT_USER')}}"
      account: "{{env_var('DBT_ACCOUNT')}}"
      database: dbt_db
      password: "{{env_var('DBT_PASSWORD')}}"
      role: dbt_role
      schema: dbt_schema
      threads: 5  
      warehouse: dbt_wh
      ##client_session_keep_alive: False
      ##query_tag: [anything]

## POSTGRES ##
## By default, edr expects the profile name 'elementary'.      ##
## Configure the database and schema of elementary models.     ##
## Check where 'elementary_test_results' is to find it.        ##

elementary:
  outputs:
    elementary_dev:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER')}}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: dbt_role
      database: dbt_db
      warehouse: dbt_wh
      schema: dbt_schema_elementary
      threads: 4