my_project_dbt:  # Nome do projeto dbt
  target: dev   # Alvo de execução (dev, prod, etc.)
  outputs:
    dev:       # Configuração do alvo 'dev'
      type: postgres
      host: 172.17.0.2    # Endereço do host do PostgreSQL
      user: postgres       # Nome do usuário do PostgreSQL
      password: mypassword  # Senha do usuário
      port: 5432         # Porta em que o PostgreSQL está rodando
      dbname: postgres       # Nome do banco de dados
      schema: public     # Esquema do banco de dados a ser utilizado
      threads: 4         # Número de threads a serem usadas pelo dbt
      keepalives_idle: 0 # Tempo de inatividade para keepalive TCP (em segundos)
