name: CD_Action

on:
  push:
    branches:
      - main

jobs:
  CD_JOB:
    runs-on: ubuntu-latest
    environment:
      name: prod

    env:
      GOOGLE_PROJECT_ID: $ {{ secrets.GOOGLE_PROJECT_ID }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WH }}
      DBT_PROFILES_DIR: ${{ vars.DBT_PROFILES_DIR }}
      DBT_PROJECT_DIR: ${{ vars.DBT_PROJECT_DIR }}
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.3
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.DBT_ENV_SECRET_PROJECT_ID }}

      - name: Copy manifest.json from Google Cloud Storage
        run: |
          gsutil cp gs://${{ vars.GCLOUD_STORAGE_PATH_MANIFEST }}/manifest.json . || echo "Manifest not found"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Dbt Debug
        run: dbt debug --target prod
      
      - name: Dbt Deps
        run: dbt deps --target prod

      - name: Run dbt Build
        run: |
          if [ -f "./manifest.json"]; then
            dbt build -s 'state:modified+' --state ./ --target prod
          else
            dbt build --target prod
          fi

      - name: Copy new manifest to Google Cloud Storage
        run:
          gsutil cp ./my_project_dbt/target/manifest.json gs://${{ vars.GCLOUD_STORAGE_PATH_MANIFEST }}/
