name: CI_Check_Sql

on:
  push:

jobs:
  ci-check-sql-formatting:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install sqlfluff==3.1.0

      - name: Verify SQL Formatting
        run: sqlfluff lint ./my_project_dbt/models/
