name: CI schema teardown on PR closed

on:
  pull_request:
    types:
      - closed

jobs:
  CI_TEARDOWN_JOB:
    runs-on: ubuntu-latest
    
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WH }}
      DBT_PROFILES_DIR: ${{ vars.DBT_PROFILES_DIR }}
      DBT_PROJECT_DIR: ${{ vars.DBT_PROJECT_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      
      - name: Get PR NUM
        id: schema_id
        run: echo "PR_NUM=${{ github.event.number }}" >> $GITHUB_ENV    
        
      - name: dbt deps
        run: dbt deps
      
      - name: Drop PR schemas
        run: |
          dbt run-operation drop_pr_schemas --args "{'PR_number':'${PR_NUM}'}"